name: Last Hit Pages Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn clean
    - run: yarn build
    - name: Commit docs file 
      uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: "commit to repo"
        author_name: last-hit-aab
    - name: github push 
      uses: ad-m/github-push-action@v0.5.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      env:
        CI: true
